### ISSUE TITLE
The examples for bold and italic are not formatted

### ISSUE THREAD

**Issue by Ragnar-F** [krafs/LevelUp#58]
In mod settings -> overhead/text message, the examples for Bold and Italic are not formatted; that is, "Bold" is not displayed in bold and "Italic" is not displayed in italic. Is that intentional?

![image](https://user-images.githubusercontent.com/1332321/150427403-9b7ff9c6-9854-4bee-8e41-e413abc4e118.png)

**Comment by krafs** [comment]
Not intentional, no. Good catch. Will fix. Thanks for reporting!
