### ISSUE TITLE
[Suggestion] Once a pawn reaches X level, stop all base game skill decay.

### ISSUE THREAD

**Issue by JDsWebService** [krafs/LevelUp#59]
I know this is mainly a UI mod for notifying when a pawn levels up. However it would be a really nice addition to allow a field in the mod settings to specify a skill level at which the base games skill decay is then turned off, and the skill stays at or above that level.

Example:

A pawn has just reached level 20 in Crafting. In the mod settings, level 20 is specified in the stop skill decay at level field. That pawn who now is level 20, will no longer gain any more levels, and his skill value (20.00) is now locked into place.

Example 2:

A pawn has just reached level 15 in Crafting. In the mod settings, level 15 is specified in the stop skill decay at level field. That pawn who is now level 15, will continue to gain levels up until level 20.00, and will stop at level 20. The skill will also not loose any levels once the level has hit level 15.

Example 3:

A new game has been started, and the pawns crafting level is at 0. In the mod settings, level 0 is specified in the stop skill decay at level field. That pawn will now gain levels in crafting, but will subsequently not loose then due to the level specified in the mod settings.

I'm not sure if your vision for this LevelUp project will strictly be a UI/Notification mod, or if you'd be willing to expand it to include what i wrote above. If you wanted to create a new mod that has this functionality, I know alot of people would be interested, as I posted this idea on /r/rimworld, and had a pretty positive response, since this type of functionality is not in any other mod. See post link below.

Thanks in advance for all your hard work, love the mod! Keep it up!

https://www.reddit.com/r/RimWorld/comments/sgl2t6/mod_request_once_a_pawn_hits_level_20_keep_him/

Post analytics: https://prnt.sc/26n36p4

**Comment by krafs** [comment]
It's an interesting idea, sure. But I really do want to keep this mod for UI only. It can get complicated really quickly, especially if people are using this mod in combination with other skill-altering mods like Mad Skills.

I'm currently in maintenance mode, so I just make sure this mod keeps working. I don't have time to make new ones at the moment.

Have you contacted the author of Mad Skills? His repository is here: https://github.com/Ratysz/MadSkills
Apparently, that mod cannot do exactly what you're asking for, but he might be open to adding it as a feature.

**Comment by JDsWebService** [comment]
I have not contacted the author of MadSkills. I was trying to see if his mod had this functionality, as in the Reddit post someone suggested that it did. However unfortunately it did not have this functionality. I will contact him via GitHub Issues, and will mention this issue. Thanks for your hard work.

**Comment by JDsWebService** [comment]
Unfortunately, his github issues are completely abandoned. He currently has 3 github issues that he has yet to fix, and his repo hasn't been updated in months. So we'll see.

**Comment by krafs** [comment]
You can always try your luck in the Mod Ideas channel on the Rimworld Discord server, and see if a different modder is interested. Good luck!
